#!/bin/bash
set -x
if [ !$$DOCKER_REPO = "jsutdb/cross-any" ]; then
    exit 0
fi
#https://docs.docker.com/docker-hub/builds/advanced/
# Register qemu-* for all supported processors except the 
# current one, but also remove all registered binfmt_misc before
docker run --rm --privileged $IMAGE_NAME /register --reset -p yes
if [ $DOCKER_TAG = "latest" ]; then
    DOCKER_TAG=$(date "+%Y%m%d")
    docker tag $IMAGE_NAME $DOCKER_REPO:$DOCKER_TAG
    docker push $DOCKER_REPO:$DOCKER_TAG
fi
for target in mips64el-c17gcc10-linux-gnuabi64 aarch64-c17gcc10-linux-gnu x86_64-c17gcc10-linux-gnu powerpc64-c17gcc10-linux-gnuabi64; do

  cat <<EOF > Dockerfile.${target%%-*}
FROM $DOCKER_REPO:
ENV crossit=$target
# prepare base env
RUN /bin/bash /crossit $target
EOF

  docker build -f Dockerfile.${target%%-*} -t $DOCKER_REPO:${target%%-*}-$DOCKER_TAG
  docker push $DOCKER_REPO:${target%%-*}-$DOCKER_TAG
  docker tag $DOCKER_REPO:${target%%-*}-$DOCKER_TAG $DOCKER_REPO:${target%%-*}-latest
  docker push $DOCKER_REPO:${target%%-*}-latest
done